name: t_store
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: ^3.8.1


# ------- PACKAGES -------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  image_picker: ^1.1.2

  # Icons
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.1

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product Specific
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.7
  path_provider: ^2.1.5


# ------- /PACKAGES END ------ #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ------ LOCAL ASSETS ------ #
  assets:
    # ending with # it will ass everything inside it
    - assets/logos/
    - assets/icons/categories/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/
  
  # ------ LOCAL FONTS ------- #
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800


 
